import { BN } from "bn.js"

export const DEEPLINK_PROTOCOL_URL_STRING = "verus";
export const DEEPLINK_PROTOCOL_URL_CURRENT_VERSION = new BN(1, 10);

export const VERUS_MOBILE_GENERIC_REQUEST_HANDLER_ID = 0;
export const VALU_MOBILE_GENERIC_REQUEST_HANDLER_ID = 1;